# Generated by Django 5.0.3 on 2024-06-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flixprimex', '0002_peliculas_url_series_url_and_more'),
    ]

    operations = [
    ]
