# Generated by Django 5.0.3 on 2024-06-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flixprimex', '0004_convertir_fecha_estreno_a_fecha'),
    ]

    operations = [
    ]
